services:
  proxy:
    image: 'registry.gitlab.com/norbertklockiewicz/designpatterns:proxy'
    container_name: proxy
    ports:
      - "4000:4000"
    build:
      context: /proxy
      dockerfile: Dockerfile

  client:
    image: 'registry.gitlab.com/norbertklockiewicz/designpatterns:client'
    container_name: client
    ports:
      - "80:3000"
    build:
      context: /client
      dockerfile: Dockerfile
    depends_on:
      - proxy

  db_1:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3301:3306"
    volumes:
      - db_1:/var/lib/mysql
  db_2:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3302:3306"
    volumes:
      - db_2:/var/lib/mysql
  db_3:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3303:3306"
    volumes:
      - db_3:/var/lib/mysql

volumes:
    db_1:
    db_2:
    db_3:
