networks:
  dp-network:

services:
  proxy:
    image: 'registry.gitlab.com/norbertklockiewicz/designpatterns:proxy'
    networks:
      - dp-network
    container_name: proxy
    ports:
      - "4000:4000"
    build:
      context: /proxy
      dockerfile: Dockerfile

  client:
    image: 'registry.gitlab.com/norbertklockiewicz/designpatterns:client'
    container_name: client
    networks:
      - dp-network
    ports:
      - "80:3000"
    build:
      context: /client
      dockerfile: Dockerfile
    depends_on:
      - proxy

  db_1:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3301:3306"
    volumes:
      - db_1:/var/lib/mysql
  db_2:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3302:3306"
    volumes:
      - db_2:/var/lib/mysql
  db_3:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3303:3306"
    volumes:
      - db_3:/var/lib/mysql
  db_4:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3304:3306"
    volumes:
      - db_4:/var/lib/mysql
  db_5:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3305:3306"
    volumes:
      - db_5:/var/lib/mysql
  db_6:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
    volumes:
      - db_6:/var/lib/mysql
  db_7:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    volumes:
      - db_7:/var/lib/mysql
  db_8:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3308:3306"
    volumes:
      - db_8:/var/lib/mysql
  db_9:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3309:3306"
    volumes:
      - db_9:/var/lib/mysql
  db_10:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3310:3306"
    volumes:
      - db_10:/var/lib/mysql

volumes:
    client_data:
    proxy_data:
    db_1:
    db_2:
    db_3:
    db_4:
    db_5:
    db_6:
    db_7:
    db_8:
    db_9:
    db_10:
