version: '3.8'

services:
  proxy:
    container_name: proxy
    ports:
      - "4000:4000"
    build:
      context: proxy
      dockerfile: Dockerfile
    depends_on:
      - db_1
      - db_2
      - db_3
    networks:
      - load_balancer

  client:
    container_name: client
    entrypoint: /app/entrypoint.sh
    ports:
      - "80:3000"
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - load_balancer

  db_1:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3301:3306"
    volumes:
      - db_1:/var/lib/mysql
    networks:
      - load_balancer

  db_2:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3302:3306"
    volumes:
      - db_2:/var/lib/mysql
    networks:
      - load_balancer

  db_3:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3303:3306"
    volumes:
      - db_3:/var/lib/mysql
    networks:
      - load_balancer

volumes:
  db_1:
  db_2:
  db_3:


networks:
  load_balancer:
    driver: bridge
