import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {MySqlRawQueryResult} from "drizzle-orm/mysql-proxy";
import React from "react";
import {users} from "@/schema";
import {db} from "@/db";

const inter = Inter({ subsets: ["latin"] });


export type NewUser = typeof users.$inferInsert; // insert type


export default function Home() {
  async function insertUser(user: NewUser): Promise<MySqlRawQueryResult> {
    return db.insert(users).values(user);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}></div>

        <div className={styles.grid}>
          <div
            className={styles.card}
            style={{ cursor: "pointer" }}
            onClick={async () => {
              const result = await insertUser({fullName: 'John Doe'})
            }}
          >
            <h2>
              INSERT <span>-&gt;</span>
            </h2>
          </div>

          <div
            className={styles.card}
            style={{ cursor: "pointer" }}
            onClick={async () => {
              const result = await db.select().from(users);
            }}
          >
            <h2>
              SELECT <span>-&gt;</span>
            </h2>
          </div>
        </div>
      </main>
    </>
  );
}
