services:
#  web:
#    build: .
#    ports:
#      - "8000:80



  db_1:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3301:3306"
  db_2:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3302:3306"
  db_3:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3303:3306"
  db_4:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3304:3306"
  db_5:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3305:3306"
  db_6:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
  db_7:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
  db_8:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3308:3306"
  db_9:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3309:3306"
  db_10:
    image: 'mysql:latest'
    env_file:
      - mysql.env
    ports:
      - "3310:3306"